# Generated by Django 4.2.7 on 2026-05-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='fanfics.category'),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='fandoms',
            field=models.ManyToManyField(blank=True, null=True, to='fanfics.fandom'),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='fanfics.tag'),
        ),
    ]
