# Generated by Django 5.2.12 on 2026-04-02 17:07

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0003_alter_comment_chapter_follow_notification_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='fanfic',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='link',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='message',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='reason',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
