# Generated by Django 5.2.12 on 2026-04-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0004_remove_follow_fanfic_remove_follow_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanfic',
            old_name='sinopse',
            new_name='synopsis',
        ),
    ]
