# Generated by Django 4.2.7 on 2026-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0005_rename_sinopse_fanfic_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.TextField(),
        ),
    ]
